version: '3.8'

services:
  rev_proxy:
    container_name: linebot-rev_proxy
    build: ./rev_proxy
    image: linebot-rev_proxy
    networks:
      - internal
      - external
    ports:
      - 4545:4040 # For inspecting ngrok status
    command: ngrok http bot_srv:5555
  bot_srv:
    container_name: linebot-bot
    build: ./bot
    image: linebot-bot
    working_dir: /linebot
    volumes:
      - ./bot:/linebot
    networks:
      - internal
      - external
    command: waitress-serve --listen bot_srv:5555 bot:app

networks:
  internal:
    internal: true
  external:
